name: Run Python Tests
on: 
  push:
    branches:
      - development
      - autotest
  
  pull_request:
    branches: 
      - staging  

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env DATABRICKS_JOB_ID
        if: github.ref_name == 'master'
        run: echo "DATABRICKS_JOB_ID=24245" >> "$GITHUB_ENV"
      - name: Set env DATABRICKS_JOB_ID
        if: github.ref_name == 'main'
        run: echo "DATABRICKS_JOB_ID=32757" >> "$GITHUB_ENV"
      - name: Echo $DATABRICKS_JOB_ID
        run: echo $DATABRICKS_JOB_ID
          
