name: Run Python Tests
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      env:
        XRAY_USERNAME: ${{ secrets.XRAY_USERNAME }}
      run: |
        example-command "$XRAY_USERNAME"
