name: Run Python Tests
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip -V
          pip install --trusted-host pypi.python.org --trusted-host files.pythonhosted.org --trusted-host pypi.org pip-tools
          pip install --trusted-host pypi.python.org --trusted-host files.pythonhosted.org -U pytest
          pip install --trusted-host pypi.python.org --trusted-host files.pythonhosted.org -U python-dotenv
      - name: Run tests with pytest
        env:
          XRAY_USERNAME: ${{secrets.XRAY_USERNAME}}
        run: pytest
