name: Run Python Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set the value
        id: step_one
        run: |
          DATA_BRICK_CLIENT=testing
          echo "action_state=yellow" >> $GITHUB_ENV
          echo ::set-output name=databricks-client::$DATA_BRICK_CLIENT
          
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.action_state }}" # This will output 'yellow'
          echo "${{ steps.step_one.databricks-client }}"
        
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with pytest
        run: pytest
