name: Run Python Tests - Core
on: 
  push:
    branches:
      - development
  
  pull_request:
    branches: 
      - staging  

  workflow_dispatch:

jobs:
  test-development:
    name: Run Test Automation on Development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Echo
        run: |
          echo ${{ github.ref }}
          echo ${{ github.base_ref }}
          echo ${{ github.head_ref }}
          echo ${{ github.ref_name }}
          
