name: Run Python Tests - Core
on: 
  push:
    branches:
      - development
      - staging
      - main
  
  workflow_dispatch:

jobs:
  test:
    name: Run Test Automation
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Echo
        run: |
          echo 'Test Test'
          echo ${{ github.event_name }}
          echo ${{ github.ref_name }}
          
  test-demand:
    name: Run Test Automation on Demand
    runs-on: [self-hosted]
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v2
      - name: Echo
        run: |
          echo 'On Demad Test'
          echo ${{ github.event_name }}
          echo ${{ github.ref_name }}
          echo "ENV_PREFIX=DEV" >> $GITHUB_ENV
          echo ${{ ENV_PREFIX }}
          echo ${{ env.ENV_PREFIX }}

  test-staging:
    name: Run Test Automation on Staging
    runs-on: [self-hosted]
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Echo
        run: |
          echo 'Push Test'
          echo ${{ github.event_name }}
          echo ${{ github.ref_name }}

          
