name: Workflow One

on:
  push:
    branches: 
        - autotest  
jobs:

    workflow_job:
        name: Run Workflow One
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Echo
              run: |
                echo 'Test Workflow One'
                echo ${{ github.event_name }}
                echo ${{ github.ref_name }}